### ISSUE TITLE
Accept header validation crashes the application when an endpoint is requested by a browser

### ISSUE THREAD

**Issue by JoostPON** [ponbike/openapi-express#51]
Since version 1.6.0 there is a strict validation on accept header. This causes the application to crash when an endpoint is requested via a browser.

I've logged the accept header that is being tested: `text/html,application/xhtml+xml,application/xml`
The endpoint works properly when I request it via Insomnia/Postman with `*/*` as accept header

```
/node_modules/content-type/index.js:127
    throw new TypeError('invalid media type')
          ^

TypeError: invalid media type
    at Object.parse (/node_modules/content-type/index.js:127:11)
    at setCharset (/node_modules/express/lib/utils.js:254:28)
    at ServerResponse.send (/node_modules/express/lib/response.js:174:32)
    at ServerResponse.json (/node_modules/express/lib/response.js:278:15)
    at ServerResponse.send (/node_modules/express/lib/response.js:162:21)
    at /node_modules/@hckrnews/express-callback/src/express-callback.js:57:41
```

**Comment by pieter-pon** [comment]
Since: https://github.com/ponbike/openapi-express/pull/50

Deps:

- https://github.com/hckrnews/express-callback/pull/20/files
- https://github.com/hckrnews/express-callback/pull/21/files
- https://github.com/hckrnews/express-callback/pull/22/files
- https://github.com/ponbike/openapi-routes/pull/16/files

**Comment by pieter-pon** [comment]
@JoostPON In version 1.6.1 it doesn't listen anymore to the accept header.
In your API you can e.g. use `context.request.headers.accept` to know the header from the request.

To send a content type to the response header, you should send it from your controller.

```javascript
{
        statusCode: 200,
        body,
        headers: {
          'Content-Type': 'application/json'
        }
}
```
